sitewide_alerts.settings:
  type: mapping
  label: Settings
  mapping:
    site_alert_active:
      type: boolean
    site_alert_position:
      type: string
    site_alert_merge:
      type: boolean
    site_alert_expiration:
      type: string
